#!/bin/bash

recipients="foo@example,com,bar@example.org"
mail_cmd="/usr/bin/mail.mailutils"
last_ip_file="/var/cache/ip_address"
last_ip=$(cat ${last_ip_file})
my_hostname=$(/bin/hostname)
dig_timeout=5

if my_ip=$(timeout -s KILL $dig_timeout /bin/dig -4 +short ANY  @resolver1.opendns.com myip.opendns.com); then
    if [[ ${my_ip} != ${last_ip} ]]; then
        echo "The IP address has changed from ${last_ip} to ${my_ip}" |
        ${mail_cmd} -s "NOTICE: IP address has changed for host ${my_hostname}" ${recipients}
        
        echo ${my_ip} > ${last_ip_file}
    fi  
else
    echo "Error: Unable to obtain external IP address"
fi
